### ISSUE TITLE
Poszukajmy kolorowych i ciekawych zdjęć

### ISSUE THREAD

**Issue by ukostuch** [AGH-Narzedzia-Informatyczne-2022-2023/dream_team#4]
**Jeśli na naszej stronie zamieścimy zdjęcia, które przykuwają uwagę to strona będzie dla użytkowników dużo bardziej interesująca**
**Przykładowe zdjęcie które wydało mi się ciekawe:**
![koncert](https://user-images.githubusercontent.com/115481400/201340684-e407fdea-6294-406a-beeb-fc182664c439.jpg)

**Comment by dagmarakrenich** [comment]
Świetny pomysł!
